# Generated by Django 3.2.3 on 2021-05-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sport',
            name='is_fun',
            field=models.BooleanField(default=True),
        ),
    ]
