# Generated by Django 3.2.3 on 2021-05-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210527_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='location',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
