# Generated by Django 3.2.3 on 2021-05-31 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210528_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='is_fun',
        ),
        migrations.AddField(
            model_name='athlete',
            name='hometown',
            field=models.TextField(default='outdoors', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='gear_needed',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('E', 'ESPN'), ('F', 'Fox Sports'), ('R', 'RedBull TV')], default='E', max_length=1)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sport')),
            ],
        ),
    ]
