# Generated by Django 3.2.3 on 2021-05-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210531_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='sport',
        ),
        migrations.AddField(
            model_name='channel',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sport'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.TextField(max_length=100),
        ),
    ]
