# Generated by Django 3.2.3 on 2021-05-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210531_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel',
            new_name='sport',
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='fox', max_length=100),
            preserve_default=False,
        ),
    ]
